# Generated by Django 2.1 on 2018-08-21 10:23

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apprentice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name=' ФИО')),
                ('tel', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name=' номер телефона')),
                ('email', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name=' email ')),
                ('info', models.CharField(blank=True, default='None', max_length=164, null=True, verbose_name='информация об ученике если нужно')),
                ('is_active', models.BooleanField(default='True', verbose_name='Активен ')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='helful_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField(blank=True, default='None', null=True, verbose_name='описание полное если нужно ')),
                ('english_name', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name='английское название для фильтра ')),
                ('is_active', models.BooleanField(default='True', verbose_name='вкл? ')),
                ('name', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name='имя на русском без html иногда нужно ')),
            ],
            options={
                'verbose_name': 'полезная инф.',
                'verbose_name_plural': 'полезная инф.',
            },
        ),
        migrations.CreateModel(
            name='masseger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name=' ФИО')),
                ('subject', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name='тема сообщения ')),
                ('mail', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name='электронная почта ')),
                ('sms', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name=' сообщение')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='Post_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name='имя категории в навигации ')),
                ('description', tinymce.models.HTMLField(default='None', null=True, verbose_name='описание категории сюда можно поместить целую статью в html ')),
                ('image', models.ImageField(blank=True, help_text='загрузите сюда изображение для категории это будет в плитках навигации', upload_to='static/media/categories_images/', verbose_name=' главное изображение для категории')),
                ('is_active', models.BooleanField(default='True', verbose_name='Включить категорию на сайт? ')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name='имя статьи кратко это будет в меню навигации')),
                ('description', tinymce.models.HTMLField(blank=True, default='None', max_length=64, null=True, verbose_name=' все описание статьи можно вставлять код html целиком')),
                ('is_active', models.BooleanField(default='True', verbose_name=' выложить статью на сайт ')),
                ('categories', models.ForeignKey(blank=True, default='None', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='sundrums_admin.Post_categories', verbose_name=' ')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name=' имя слайда')),
                ('image', models.ImageField(blank=True, default='None', help_text='изображения для слайда', max_length=64, upload_to='sliders_images/', verbose_name='путь к картинке')),
                ('description', models.CharField(blank=True, default='None', max_length=250, null=True, verbose_name=' описание или содержание слайда')),
                ('link', models.CharField(blank=True, default='#featured-services', max_length=64, null=True, verbose_name='ссылка если нужна')),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='добавить для вывода на основной странице?')),
                ('active_slide', models.CharField(blank=True, default='None', max_length=16, null=True, verbose_name='активный ли это слайд (внимание написать active только для первого слайда в остальных случаях пустое значение) ')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name='ФИО ')),
                ('tel', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name='Номер телефона ')),
                ('email', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name='адрес почты ')),
                ('info', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name='информация об учителе ')),
                ('is_active', models.BooleanField(default='True', verbose_name='Учитель работает ')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='tipe_kurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name='имя курса ')),
                ('info_kurs', tinymce.models.HTMLField(blank=True, default='None', null=True, verbose_name=' описание')),
                ('is_active', models.BooleanField(default='True', verbose_name='Курс активен?')),
                ('teacher_kurs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurs', to='sundrums_admin.teacher', verbose_name=' ')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.AddField(
            model_name='apprentice',
            name='kurs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apprentice', to='sundrums_admin.tipe_kurs', verbose_name=' '),
        ),
    ]
