# Generated by Django 2.1 on 2018-08-21 13:21

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sundrums_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name='название темы для формы ')),
            ],
            options={
                'verbose_name': 'тема для обратной связи',
                'verbose_name_plural': 'темы для обратной связи',
            },
        ),
        migrations.AlterField(
            model_name='apprentice',
            name='email',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name=' email '),
        ),
        migrations.AlterField(
            model_name='apprentice',
            name='info',
            field=models.CharField(blank=True, default=' ', max_length=164, null=True, verbose_name='информация об ученике если нужно'),
        ),
        migrations.AlterField(
            model_name='apprentice',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name=' ФИО'),
        ),
        migrations.AlterField(
            model_name='apprentice',
            name='tel',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name=' номер телефона'),
        ),
        migrations.AlterField(
            model_name='helful_information',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default=' ', null=True, verbose_name='описание полное если нужно '),
        ),
        migrations.AlterField(
            model_name='helful_information',
            name='english_name',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name='английское название для фильтра '),
        ),
        migrations.AlterField(
            model_name='helful_information',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name='имя на русском без html иногда нужно '),
        ),
        migrations.AlterField(
            model_name='masseger',
            name='mail',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name='электронная почта '),
        ),
        migrations.AlterField(
            model_name='masseger',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name=' ФИО'),
        ),
        migrations.AlterField(
            model_name='masseger',
            name='sms',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name=' сообщение'),
        ),
        migrations.AlterField(
            model_name='masseger',
            name='subject',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name='тема сообщения '),
        ),
        migrations.AlterField(
            model_name='post_categories',
            name='description',
            field=tinymce.models.HTMLField(default=' ', null=True, verbose_name='описание категории сюда можно поместить целую статью в html '),
        ),
        migrations.AlterField(
            model_name='post_categories',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name='имя категории в навигации '),
        ),
        migrations.AlterField(
            model_name='posts',
            name='categories',
            field=models.ForeignKey(blank=True, default=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='sundrums_admin.Post_categories', verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default=' ', max_length=64, null=True, verbose_name=' все описание статьи можно вставлять код html целиком'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name='имя статьи кратко это будет в меню навигации'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='active_slide',
            field=models.CharField(blank=True, default=' ', max_length=16, null=True, verbose_name='активный ли это слайд (внимание написать active только для первого слайда в остальных случаях пустое значение) '),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.CharField(blank=True, default=' ', max_length=250, null=True, verbose_name=' описание или содержание слайда'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, default=' ', help_text='изображения для слайда', max_length=64, upload_to='sliders_images/', verbose_name='путь к картинке'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name=' имя слайда'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name='адрес почты '),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='info',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name='информация об учителе '),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name='ФИО '),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tel',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name='Номер телефона '),
        ),
        migrations.AlterField(
            model_name='tipe_kurs',
            name='info_kurs',
            field=tinymce.models.HTMLField(blank=True, default=' ', null=True, verbose_name=' описание'),
        ),
        migrations.AlterField(
            model_name='tipe_kurs',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name='имя курса '),
        ),
    ]
