# Generated by Django 2.1 on 2018-08-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundrums_admin', '0005_auto_20180822_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='helful_information',
            name='name_rus',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name='имя на русском без html иногда нужно '),
        ),
        migrations.AlterField(
            model_name='helful_information',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name='название'),
        ),
    ]
