# Generated by Django 2.1 on 2018-08-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundrums_admin', '0006_auto_20180822_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, help_text='фото преподователя', upload_to='static/media/post_images/', verbose_name='фото преподавателя'),
        ),
    ]
