# Generated by Django 2.1 on 2018-08-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundrums_admin', '0008_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name=' фио кто оставил отзыв'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='prof_reviewrs',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='профессия того кто оставил отзыв '),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text_review',
            field=models.CharField(blank=True, default='', max_length=2054, null=True, verbose_name='текст отзыва '),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='название темы для формы '),
        ),
    ]
