# Generated by Django 2.1 on 2018-08-25 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sundrums_admin', '0009_auto_20180823_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='masseger',
            name='tel',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name=' сообщение'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='is_active',
            field=models.BooleanField(default='True', verbose_name='вкл? '),
        ),
        migrations.AlterField(
            model_name='apprentice',
            name='kurs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apprentice', to='sundrums_admin.tipe_kurs', verbose_name='здесь можно выбрать курс к которому прекрипить ученика'),
        ),
    ]
