# Generated by Django 2.1 on 2018-08-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundrums_admin', '0010_auto_20180825_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='socbutton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name=' название')),
                ('link', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name='ссылка')),
                ('icon', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name='иконка с fontawesome.com ')),
            ],
            options={
                'verbose_name': 'соцкнопка',
                'verbose_name_plural': 'соцкнопки',
            },
        ),
    ]
