# Generated by Django 2.1 on 2018-08-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundrums_admin', '0011_socbutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='socbutton',
            name='is_active',
            field=models.BooleanField(default='True', verbose_name='вкл? '),
        ),
    ]
