# Generated by Django 2.1 on 2018-08-30 10:02

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sundrums_admin', '0012_socbutton_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='kurs_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name='имя видео')),
                ('video_link', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name='ссылка на видео из ютуба')),
                ('text', tinymce.models.HTMLField(verbose_name=' текст статьи поста ')),
                ('tipe_kurs', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_video', to='sundrums_admin.tipe_kurs', verbose_name='в какой курс добавлять')),
            ],
            options={
                'verbose_name': 'статья с видео для курса',
                'verbose_name_plural': 'статьи с видео для курсов',
            },
        ),
    ]
