# Generated by Django 2.1 on 2018-08-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundrums_admin', '0013_kurs_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipe_kurs',
            name='image',
            field=models.ImageField(blank=True, help_text='фото преподователя', upload_to='static/media/kurs_images/', verbose_name='фото преподавателя'),
        ),
        migrations.AlterField(
            model_name='kurs_video',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='имя видео'),
        ),
        migrations.AlterField(
            model_name='kurs_video',
            name='video_link',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='ссылка на видео из ютуба'),
        ),
    ]
