# Generated by Django 2.1 on 2018-08-30 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sundrums_admin', '0014_auto_20180830_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs_video',
            name='tipe_kurs',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postkurs', to='sundrums_admin.tipe_kurs', verbose_name='в какой курс добавлять'),
        ),
        migrations.AlterField(
            model_name='tipe_kurs',
            name='teacher_kurs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurs', to='sundrums_admin.teacher', verbose_name=' преподаватель'),
        ),
    ]
