# Generated by Django 2.1 on 2018-08-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundrums_admin', '0016_auto_20180830_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipe_kurs',
            name='password',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name='пароль для открытия статии '),
        ),
        migrations.AlterField(
            model_name='tipe_kurs',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name='имя курса '),
        ),
    ]
