# Generated by Django 2.1 on 2018-08-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundrums_admin', '0017_auto_20180830_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipe_kurs',
            name='password',
            field=models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='пароль для открытия статии (если оставить 0 то пароль запрашиваться не будет)) '),
        ),
    ]
