# Generated by Django 2.1 on 2018-09-06 10:47

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sundrums_admin', '0018_auto_20180831_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ing', models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name='имя категории ')),
                ('name', models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name='имя категории на английском для фильтра ')),
                ('is_active', models.BooleanField(default='True', verbose_name='вкл?')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='product_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='имя видео')),
                ('video_link', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='ссылка на видео из ютуба')),
                ('text', tinymce.models.HTMLField(verbose_name=' текст статьи поста ')),
                ('tipe_product', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postproduct', to='sundrums_admin.tipe_kurs', verbose_name='к какому продукту добавлять')),
            ],
            options={
                'verbose_name': 'статья с видео для товара',
                'verbose_name_plural': 'статьи с видео для товара',
            },
        ),
        migrations.CreateModel(
            name='tipe_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name='имя курса ')),
                ('info_product', tinymce.models.HTMLField(blank=True, default=' ', null=True, verbose_name=' описание')),
                ('image', models.ImageField(blank=True, help_text='фото преподователя', upload_to='static/media/kproduct_images/', verbose_name='фото преподавателя')),
                ('is_active', models.BooleanField(default='True', verbose_name='вкл?')),
                ('categories_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='sundrums_admin.categories_product', verbose_name=' преподаватель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
