# Generated by Django 2.1 on 2018-09-06 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sundrums_admin', '0019_categories_product_product_video_tipe_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories_product',
            options={'verbose_name': 'категория товара', 'verbose_name_plural': 'категории товаров'},
        ),
    ]
