# Generated by Django 2.1 on 2018-09-06 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sundrums_admin', '0020_auto_20180906_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_video',
            name='tipe_product',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postproduct', to='sundrums_admin.tipe_product', verbose_name='к какому продукту добавлять'),
        ),
    ]
