# Generated by Django 2.1 on 2018-09-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundrums_admin', '0021_auto_20180906_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories_product',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name='имя категории '),
        ),
        migrations.AlterField(
            model_name='categories_product',
            name='name_ing',
            field=models.CharField(blank=True, default=' ', max_length=64, null=True, verbose_name='имя категории на английском для фильтра '),
        ),
    ]
